name: Supabase Keep Alive

on:
  schedule:
    - cron: '0 12 */4 * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping site
        run: |
          curl -I https://minigolf-storage.vercel.app/
